server:
  port: 8082
spring:  
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
    metadata-map:
      zone : A
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  